# Generated by Django 6.0.3 on 2026-04-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_role_user_is_phone_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_phone_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                max_length=20,
            ),
        ),
    ]
